export const AIRLINES = [
  "Delta Air Lines",
  "United Airlines",
  "American Airlines",
  "Southwest Airlines",
  "Alaska Airlines",
  "JetBlue",
  "Frontier Airlines",
  "Hawaiian Airlines",
  "Air Canada",
  "WestJet",
  "LATAM Airlines",
  "Avianca",
  "Aeromexico",
  "Copa Airlines",
  "Lufthansa",
  "British Airways",
  "Air France",
  "KLM",
  "Turkish Airlines",
  "Swiss International",
  "Austrian Airlines",
  "Virgin Atlantic",
  "Iberia",
  "Finnair",
  "Brussels Airlines",
  "TAP Air Portugal",
  "Ryanair",
  "easyJet",
  "Wizz Air",
  "Norwegian Air",
  "Emirates",
  "Qatar Airways",
  "Etihad Airways",
  "flydubai",
  "Air Arabia",
  "Ethiopian Airlines",
  "EgyptAir",
  "Kenya Airways",
  "Singapore Airlines",
  "ANA (All Nippon Airways)",
  "Japan Airlines",
  "Cathay Pacific",
  "Korean Air",
  "EVA Air",
  "Air China",
  "China Southern Airlines",
  "China Eastern Airlines",
  "IndiGo",
  "AirAsia",
  "Air New Zealand",
];
