// Client-side split sheet PDF generator using window.print()

interface SplitEntry {
  contributor?: { name: string; pro_affiliation?: string; ipi_number?: string; publisher_name?: string };
  role: string;
  master_pct?: number | null;
  producer_pct?: number | null;
  writer_pct?: number | null;
  publisher_pct?: number | null;
}

interface SplitSong {
  title: string;
  entries: SplitEntry[];
}

interface SplitSheetData {
  projectName: string;
  projectType: string;
  songs: SplitSong[];
}

export function generateSplitSheetPdf(data: SplitSheetData) {
  const html = buildHtml(data);
  const win = window.open("", "_blank");
  if (!win) return;
  win.document.write(html);
  win.document.close();
  // Allow images/fonts to load
  setTimeout(() => win.print(), 400);
}

function buildHtml(data: SplitSheetData): string {
  const typeLabel = data.projectType === "ep" ? "EP" : data.projectType === "album" ? "Album" : "Single";

  const songsHtml = data.songs
    .map(
      (song, idx) => `
    <div class="song-section">
      <h3>Track ${idx + 1}: ${esc(song.title)}</h3>
      <table>
        <thead>
          <tr>
            <th>Contributor</th>
            <th>Role</th>
            <th>PRO</th>
            <th>IPI #</th>
            <th>Publisher</th>
            <th>Master %</th>
            <th>Producer %</th>
            <th>Writer %</th>
            <th>Pub %</th>
          </tr>
        </thead>
        <tbody>
          ${song.entries
            .map(
              (e) => `
            <tr>
              <td>${esc(e.contributor?.name || "—")}</td>
              <td>${esc(e.role.replace("_", " "))}</td>
              <td>${esc(e.contributor?.pro_affiliation || "—")}</td>
              <td>${esc(e.contributor?.ipi_number || "—")}</td>
              <td>${esc(e.contributor?.publisher_name || "—")}</td>
              <td>${e.master_pct ?? "—"}</td>
              <td>${e.producer_pct ?? "—"}</td>
              <td>${e.writer_pct ?? "—"}</td>
              <td>${e.publisher_pct ?? "—"}</td>
            </tr>
          `
            )
            .join("")}
        </tbody>
      </table>
      <div class="signatures">
        <p class="sig-header">Signatures</p>
        ${song.entries
          .map(
            (e) => `
          <div class="sig-line">
            <div class="sig-name">${esc(e.contributor?.name || "—")}</div>
            <div class="sig-field"><span>Signature:</span> <span class="underline"></span></div>
            <div class="sig-field"><span>Date:</span> <span class="underline short"></span></div>
          </div>
        `
          )
          .join("")}
      </div>
    </div>
  `
    )
    .join("");

  return `<!DOCTYPE html>
<html>
<head>
<title>Split Sheet — ${esc(data.projectName)}</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; padding: 40px; color: #111; font-size: 13px; }
  h1 { font-size: 22px; margin-bottom: 4px; }
  h2 { font-size: 14px; color: #666; font-weight: 500; margin-bottom: 24px; }
  h3 { font-size: 15px; margin-bottom: 8px; border-bottom: 2px solid #111; padding-bottom: 4px; }
  .song-section { margin-bottom: 32px; page-break-inside: avoid; }
  table { width: 100%; border-collapse: collapse; margin-bottom: 16px; }
  th, td { border: 1px solid #ccc; padding: 6px 8px; text-align: left; font-size: 12px; }
  th { background: #f5f5f5; font-weight: 600; }
  td { white-space: nowrap; }
  .signatures { margin-top: 16px; }
  .sig-header { font-weight: 600; margin-bottom: 8px; font-size: 13px; }
  .sig-line { display: flex; gap: 16px; align-items: flex-end; margin-bottom: 24px; }
  .sig-name { width: 140px; font-weight: 500; }
  .sig-field { display: flex; gap: 4px; align-items: flex-end; }
  .sig-field span { white-space: nowrap; }
  .underline { display: inline-block; width: 200px; border-bottom: 1px solid #111; }
  .underline.short { width: 100px; }
  @media print {
    body { padding: 20px; }
    .song-section { page-break-inside: avoid; }
  }
</style>
</head>
<body>
  <h1>${esc(data.projectName)}</h1>
  <h2>${typeLabel} — Split Sheet</h2>
  ${songsHtml}
  <p style="margin-top:32px;font-size:11px;color:#999;">Generated by Rollout • ${new Date().toLocaleDateString()}</p>
</body>
</html>`;
}

function esc(str: string): string {
  return str.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}
