project_id = "ctnsworqzzguykzzvdme"

[functions]
  [functions.accept-invite]
    verify_jwt = false
  [functions.approve-split]
    verify_jwt = false
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.scrape-chartmasters]
    verify_jwt = false
  [functions.send-split-approval]
    verify_jwt = false
  [functions.spotify-search]
    verify_jwt = false
  [functions.send-notification]
    verify_jwt = false
  [functions.send-digest]
    verify_jwt = false
