
INSERT INTO public.industry_entities (name, entity_type, is_custom, source)
VALUES
  ('DistroKid', 'distributor', false, 'spotify_providers'),
  ('CD Baby', 'distributor', false, 'spotify_providers'),
  ('EmuBands', 'distributor', false, 'spotify_providers'),
  ('Record Union', 'distributor', false, 'spotify_providers'),
  ('Amuse', 'distributor', false, 'spotify_providers'),
  ('RouteNote', 'distributor', false, 'spotify_providers'),
  ('SoundOn', 'distributor', false, 'spotify_providers'),
  ('recordJet', 'distributor', false, 'spotify_providers'),
  ('LANDR', 'distributor', false, 'spotify_providers'),
  ('MUGO', 'distributor', false, 'spotify_providers'),
  ('VIEENT', 'distributor', false, 'spotify_providers'),
  ('Too Lost', 'distributor', false, 'spotify_providers'),
  ('TuneCore', 'distributor', false, 'spotify_providers'),
  ('Proton', 'distributor', false, 'spotify_providers'),
  ('Random Sounds', 'distributor', false, 'spotify_providers'),
  ('ROC Nation Distribution', 'distributor', false, 'spotify_providers'),
  ('Horus Music', 'distributor', false, 'spotify_providers'),
  ('Wiseband', 'distributor', false, 'spotify_providers'),
  ('Catapult', 'distributor', false, 'spotify_providers'),
  ('The Orchard', 'distributor', false, 'spotify_providers'),
  ('Believe', 'distributor', false, 'spotify_providers'),
  ('FUGA', 'distributor', false, 'spotify_providers'),
  ('InnerCat Music Group', 'distributor', false, 'spotify_providers'),
  ('ZVONKO digital', 'distributor', false, 'spotify_providers'),
  ('Soulspazm', 'distributor', false, 'spotify_providers'),
  ('ampsuite', 'distributor', false, 'spotify_providers'),
  ('Vydia', 'distributor', false, 'spotify_providers'),
  ('IDOL', 'distributor', false, 'spotify_providers'),
  ('Kontor New Media', 'distributor', false, 'spotify_providers'),
  ('ONErpm', 'distributor', false, 'spotify_providers'),
  ('ZEBRALUTION', 'distributor', false, 'spotify_providers'),
  ('e-Muzyka', 'distributor', false, 'spotify_providers'),
  ('Symphonic', 'distributor', false, 'spotify_providers'),
  ('Secretly Distribution', 'distributor', false, 'spotify_providers'),
  ('Cinq Music Group', 'distributor', false, 'spotify_providers'),
  ('Syntax Creative', 'distributor', false, 'spotify_providers'),
  ('dig dis!', 'distributor', false, 'spotify_providers'),
  ('Redeye Worldwide', 'distributor', false, 'spotify_providers'),
  ('Black Hole Recordings', 'distributor', false, 'spotify_providers'),
  ('Downtown Artist & Label Services', 'distributor', false, 'spotify_providers'),
  ('Absolute Label Services', 'distributor', false, 'spotify_providers'),
  ('Label Engine', 'distributor', false, 'spotify_providers'),
  ('EWWAY', 'distributor', false, 'spotify_providers'),
  ('Identity Music', 'distributor', false, 'spotify_providers'),
  ('MUSICADDERS', 'distributor', false, 'spotify_providers'),
  ('Euphoria', 'distributor', false, 'spotify_providers'),
  ('Xelon Digital', 'distributor', false, 'spotify_providers'),
  ('Revelator', 'distributor', false, 'spotify_providers'),
  ('iGroove', 'distributor', false, 'spotify_providers'),
  ('Republic of Music', 'distributor', false, 'spotify_providers'),
  ('Fole Publishing', 'distributor', false, 'spotify_providers'),
  ('Wide Awake Music', 'distributor', false, 'spotify_providers'),
  ('DSTRO7', 'distributor', false, 'spotify_providers'),
  ('Cargo Records UK', 'distributor', false, 'spotify_providers'),
  ('TAKWENE', 'distributor', false, 'spotify_providers'),
  ('Pirames International', 'distributor', false, 'spotify_providers'),
  ('LabelWorx', 'distributor', false, 'spotify_providers'),
  ('NEWS NV', 'distributor', false, 'spotify_providers'),
  ('FaroLatino', 'distributor', false, 'spotify_providers'),
  ('Armada Distribution', 'distributor', false, 'spotify_providers'),
  ('Entertainment Factory', 'distributor', false, 'spotify_providers'),
  ('Precise Digital', 'distributor', false, 'spotify_providers'),
  ('!K7 Music', 'distributor', false, 'spotify_providers'),
  ('EVEARA', 'distributor', false, 'spotify_providers'),
  ('Diskover Co.', 'distributor', false, 'spotify_providers'),
  ('Feiyr', 'distributor', false, 'spotify_providers'),
  ('Kartel Music Group', 'distributor', false, 'spotify_providers'),
  ('DANMARK', 'distributor', false, 'spotify_providers'),
  ('Uniqueopia', 'distributor', false, 'spotify_providers'),
  ('Independent Digital', 'distributor', false, 'spotify_providers'),
  ('Qanawat Music', 'distributor', false, 'spotify_providers'),
  ('Jamvana', 'distributor', false, 'spotify_providers'),
  ('Virgin Music Group', 'distributor', false, 'spotify_providers'),
  ('Next Music', 'distributor', false, 'spotify_providers'),
  ('Rebeat Digital', 'distributor', false, 'spotify_providers'),
  ('Sundesire Media Worx', 'distributor', false, 'spotify_providers'),
  ('Integral', 'distributor', false, 'spotify_providers'),
  ('ALOADED', 'distributor', false, 'spotify_providers'),
  ('Metropolitan Groove Merchants', 'distributor', false, 'spotify_providers'),
  ('Nudacy', 'distributor', false, 'spotify_providers'),
  ('AEI Music', 'distributor', false, 'spotify_providers'),
  ('Streambay', 'distributor', false, 'spotify_providers'),
  ('TuStreams', 'distributor', false, 'spotify_providers'),
  ('YG PLUS', 'distributor', false, 'spotify_providers'),
  ('PLATOON', 'distributor', false, 'spotify_providers'),
  ('Alter K', 'distributor', false, 'spotify_providers'),
  ('Watary', 'distributor', false, 'spotify_providers'),
  ('Disetti Music', 'distributor', false, 'spotify_providers'),
  ('EMS', 'distributor', false, 'spotify_providers'),
  ('Labelcamp', 'distributor', false, 'spotify_providers'),
  ('AudioSalad', 'distributor', false, 'spotify_providers'),
  ('SonoSuite', 'distributor', false, 'spotify_providers'),
  ('LabelGrid', 'distributor', false, 'spotify_providers')
ON CONFLICT DO NOTHING;
