
INSERT INTO public.rolly_knowledge (source, chapter, content) VALUES

-- MasterClass: How to Make a Music Video
('masterclass_music_video', 'Music Video Production: Overview', 'Music videos are a form of digital media where a song plays over a film that echoes a theme, story, or message in the music and lyrics. They play a major role in advancing the music career of a band or artist. Uploading the final video to websites and social media can unlock new avenues to reach listeners and market the song to boost record sales.'),

('masterclass_music_video', 'Music Video Production: Step-by-Step Process', 'Step 1: Establish a concept — work closely with the artist to develop a concept or story. Research references to other video content for initial ideas and storyboards. Step 2: Budget accordingly — after deciding the concept (which dictates actors and locations), begin working on a budget considering crew members, actors, and equipment. Step 3: Scout locations and take photos — assemble several location options considering power access, lighting at intended shoot time, and available space for movement. Step 4: Build your storyboard — map out the video shot by shot with lens types, camera angles, and blocking for each shot.'),

('masterclass_music_video', 'Music Video Production: Shoot & Post-Production', 'Step 5: Assemble crew and equipment — determine which cameras, lighting instruments, and whether a green screen is needed. Music videos typically employ a gaffer, grip, sound technician, and production assistant. Step 6: Shoot the video — follow a shooting schedule with call times and meal breaks. Get extra takes so the editor has plenty of options. Step 7: Post-production — share the music track and footage with the editor who will stitch them together. Editors may add visual effects or sound effects. Step 8: Review and refine drafts — director, producer, and band members weigh in. Step 9: Finalize and share — tease bits online leading up to release, then upload to video platforms, website, and social media.'),

('masterclass_music_video', 'Music Video Production: Pro Tips', 'Tip 1: Keep all notes and ideas in one place — a notebook or computer file for all inspirations. Tip 2: Maintain constant communication with the artist or band throughout the process to ensure the product matches their vision. Tip 3: Know the song in detail — listen at different times of day to discover fresh insights that guide production. Tip 4: Factor in rehearsal time — if there is intricate choreography or blocking, pad in rehearsal time so performers are comfortable with the movements and space.'),

-- Dependable Expendables: Music Video Production 101
('dependable_expendables_mv101', 'Music Video vs TV Production', 'Music videos are generally different from TV productions. They have shorter runtime, are more focused on showcasing the artist and music, tend to be more fast-paced with a smaller crew and budget. They have more flexibility in terms of location and visual style. However, both require careful planning, coordination, attention to detail, and strong communication skills. Both rely on directing, producing, editing, visual effects, styling, makeup, and more.'),

('dependable_expendables_mv101', 'Music Video Pre-Production: Budget & Audience', 'Key pre-production questions: 1) What is the budget? The budget impacts crew size, number of locations, equipment quality, and post-production work. Have a clear understanding to make informed resource decisions. 2) Who is the target audience? This shapes the concept and style — younger audiences may want energetic and visually appealing content, while older audiences may prefer thoughtful and introspective videos. 3) What is the concept or theme? This guides creative direction, visual style, locations, and cast.'),

('dependable_expendables_mv101', 'Music Video Production: Key Crew Roles', 'Essential crew roles for music video production: Director — oversees creative vision through camera angles, lighting, and visual elements. Producer — manages logistics including schedules, budgets, and resources. Editor — assembles footage into a cohesive narrative. Visual Effects Artist — creates special effects and digital enhancements including CGI, color/lighting enhancement, and compositing. Stylist — chooses and coordinates wardrobe appropriate for the concept. Makeup Artist & Hair Stylist — creates looks consistent with the video aesthetic.'),

('dependable_expendables_mv101', 'Music Video Production: Logistics Roles', 'Additional production roles: Location Manager — scouts and secures locations, negotiates rental agreements, obtains permits. Casting Director — finds and casts talent including actors, dancers, and extras. Production Coordinator — manages schedules for cast and crew, coordinates transportation, accommodations, and catering. Production Manager — obtains necessary filming permits, location permits, and regulatory approvals. Production Assistant — secures equipment including cameras, lighting, props, and wardrobe. Production Accountant — manages budget, tracks expenses, prepares budget reports, and reconciles accounts.');
