
INSERT INTO public.rolly_knowledge (chapter, content) VALUES

-- Berklee: Music Marketing Strategies
('Music Marketing: Singles Release Strategy', 'In today''s singles-based economy, independent artists should release one single every 6-8 weeks to maintain audience engagement and trigger algorithms on DSPs (Spotify, Apple Music) and social platforms. Consistency is a discovery strategy. Before promoting, ensure the song is competitive within your genre by getting honest feedback from industry professionals, not just friends and family. Marketing can only amplify what''s already working.'),

('Music Marketing: Online Presence Optimization', 'Your website is your central hub—a distraction-free space to showcase music, sell merch, promote shows, and collect emails. Use consistent @usernames across all platforms (add "music" or "official" if taken). Set up artist profiles on ALL major DSPs (Spotify, Apple Music, Amazon Music, YouTube Music, SoundCloud). Use Bandcamp for direct-to-fan sales with higher payouts and greater pricing control.'),

('Music Marketing: Creating a Release World', 'A release is an opportunity to build an entire world around your music. Cover art, press photos, social content, music videos, and merch design should work together to reflect the tone and mood of the music. Example: Taylor Swift''s "Eras"—each album has its own self-contained world with distinct look, feel, and storyline. That level of cohesion deepens fan connection and drives loyalty.'),

('Music Marketing: Social Media Content Strategy', 'Share more than announcements and selfies—share interests and passions outside of music that align with your ideal fans. Lean into storytelling with hooks for attention. Create a content rhythm (consistent, not necessarily daily). Tailor content per platform: short-form video for TikTok, polished visuals for Instagram, conversational for Threads/Twitter. Prioritize engagement over reach—a smaller, highly engaged fanbase is far more valuable than inflated follower counts.'),

('Music Marketing: Digital Advertising', 'You can start seeing real results with digital ads for as little as $50. Ads on Meta (Instagram/Facebook), TikTok, and YouTube are especially effective for emerging artists. Use platforms like SymphonyOS to manage campaigns. Best-performing ads look like organic content—short-form videos, lyric snippets, live clips. Target by genre, similar artists, or location. Start small and scale based on performance data.'),

('Music Marketing: Playlisting Strategy', 'Pitch songs at least 3-4 weeks before release through the DSP''s artist platform (Spotify for Artists) for editorial playlist consideration. Research independent curators—user-curated and niche playlists drive meaningful engagement and build momentum. Use SubmitHub, Groover, or social media outreach to find curators. Keep pitch messages short, personal, and professional. Avoid mass emails.'),

-- Spotify for Artists: Magic City Hippies Case Study
('Spotify Marketing Tools: Marquee Strategy', 'Marquee is an in-app full-screen recommendation shown to targeted Spotify listeners. Magic City Hippies used Marquee across 6 pre-release singles over 9 months before their album. Results: people who saw Marquees were 4x more likely to stream the singles. 25% of lapsed listeners actively streamed the band for the first time in 6+ months. On average, 24% of Marquee listeners saved singles to their library. On album release, Marquee drove 13.5 streams per listener (3x the album average). 30% intent rate (saves/playlist adds) and 20% of listeners also streamed older catalog.'),

('Spotify Marketing Tools: Canvas & Discovery Mode', 'Canvas (short looping visuals on Spotify) extends your visual world into the streaming platform and increases Instagram Story shares. Create Canvases for every single using music video clips, B-roll, or visualizers. Discovery Mode helps expand reach in algorithmic playlists by prioritizing selected tracks in personalized listening sessions. Magic City Hippies tripled their audience in Discovery Mode contexts across 100+ markets, with 31% of listeners being completely new. Discovery Mode is especially powerful in traditionally "down" months like December and for extending a release''s life post-drop.'),

-- Indie Music Secrets: Profitable Touring
('Touring Strategy: Micro-Touring & Regional Focus', 'Start touring by conquering a single region first, creating intense local buzz at intimate venues. Build your hometown/state fanbase before expanding outward. Use the Indie Venue Bible (30,000+ venues in US and Canada) to find venues. Consider alternative performance spaces: Sofar Sounds secret shows (global, pay minimum $100+, no promo needed, keep merch sales), Side Door Access (Canada), campus radio interviews, local TV spots, and community radio stations for promotion.'),

('Touring Strategy: Pre-Tour Fan Building', 'Use targeted Facebook/Instagram ads to build a local fanbase BEFORE arriving in each tour city. You can run effective campaigns for as little as $2/day. Share teasers, behind-the-scenes content, and contests. One artist got nearly 500,000 views and 10,000+ reactions from just two live performance videos over a 12-week campaign. The goal is that fans are chanting your name before you even step off the tour bus.'),

('Touring Strategy: Sponsorships & Revenue', 'Local businesses in your hometown or tour cities may want to sponsor your tour. Offer stage shout-outs, social media promotion, merch table advertising, or after-party hosting at their businesses (especially restaurants). Pre-sell merch online before the tour using on-demand dropshipping so you never hold unsold inventory. Create exclusive or city-specific designs. This generates revenue before hitting the road.'),

('Touring Strategy: Post-Tour Engagement', 'Keep momentum rolling after the tour by engaging with new fans. Stay active on social media, release behind-the-scenes content, and thank fans for coming out. Don''t go cold turkey on the cities you just developed—turn one-time attendees into lifelong superfans through consistent engagement.'),

-- Caitlin Rushing: Independent Gig Booking
('Independent Gig Booking: Systematic Approach', 'A full-time singer-songwriter played 300+ shows in 50+ cities booking independently. The system: 1) Secure accommodations first (friends/family, hotel points, Thousand Trails Cabin Pass at $1600/year for unlimited cabin stays, campgrounds at $10/night via Recreation.gov, TourSleeper fan-hosted stays, Harvest Hosts for RVers at wineries/breweries). 2) Use Roadtrippers app to find venues within an hour of lodging—it links directly to venue websites and Facebook pages. 3) Spend 1-2 hours a few times per week researching and reaching out.'),

('Independent Gig Booking: Outreach Best Practices', 'Send short Facebook messages to venues asking for the point of contact for music bookings. Include a link to your website. Use a professional email (e.g., yourname@music.com, not personal addresses). Email format: brief intro, specific travel dates, genre description, website link, professional photo, and notable achievements. Track all outreach in a Google Sheets spreadsheet with venue name, contact info, response status, and follow-up dates. Follow up 1 week before confirmed gigs to reconfirm details.'),

('Independent Gig Booking: Pre-Gig Questions', 'Before confirming any gig, ask: 1) How and when will they pay? (prefer on-site payment, especially for new venues), 2) Will they require a W-9? (needed if payment exceeds certain thresholds), 3) Will you play outside? What''s the rain contingency? (avoid uncompensated cancellations), 4) Where to load in and park? 5) What are the venue''s expectations for set length, volume, and genre? Always have clear terms established before committing.'),

-- RepostExchange: Independent Touring
('Touring: Revolving Headliner & Collaboration Model', 'Organize a "revolving headliner" tour where each artist headlines in their own city, handling local organizing and promotion. This shares the workload and maximizes attendance by leveraging each artist''s local fanbase. Use SoundCloud insights or streaming analytics to identify cities with most engaged fans. Reach out to DIY promoters with a polished EPK including video content. Always have a professional Electronic Press Kit ready.'),

('Touring: Etiquette & Relationship Building', 'Tour etiquette is critical for getting rebooked: show up on time, introduce yourself to key people, don''t get drunk/high, and treat everyone (promoters, sound engineers, other acts) with respect. Sound engineers can make or break your performance. Watch other acts on your bill—promoters notice. Follow other artists on social media, take footage of their sets (with permission), add them as collaborators. Leave gifts for promoters (free t-shirt or CD). Other acts become lifelong friends, fans, and future show-swap partners in their hometowns.'),

('Touring: Merch & Spreadsheet Organization', 'Merch is often the biggest income stream on tour. Stock t-shirts in multiple sizes, physical music (CDs, vinyl), and budget items (stickers, buttons, patches). Bring free promo items with QR codes to your music or mailing list. Accept payments via Square reader and QR codes for Venmo/CashApp. Keep a tour spreadsheet with: venue name/address/phone/parking, promoter contact details, deal terms (flat fee/percentage/door split), load-in/soundcheck/set times, accommodation details, and technical specifications/backline requirements.'),

-- WVU: DIY Band Tour Planning
('DIY Tour Planning: Route & City Research', 'Start with a manageable region—cities within a 6-10 hour radius. Route outward in one direction, then circle back through new cities on the return to avoid zig-zagging and doubling back. Before booking, research each city: 1) How active is the music scene? Check local event calendars, indie publications, college radio, social media groups. 2) What similar-sounding artists are in the area for potential collaboration? 3) What venues (DIY spaces, art galleries, breweries, house shows) align with your genre and branding?'),

('DIY Tour Planning: Booking Email Best Practices', 'Use a clear subject line: "Booking Inquiry – [Artist Name] – [City] – [Date Range]". Introduce yourself in 1-2 sentences with genre. Provide streaming links (not attachments) to Spotify/Bandcamp, social media, and live performance videos. Suggest specific dates but stay flexible. Mention local connections who could share the bill—it reassures the promoter you''ll bring an audience. Keep it short—talent buyers don''t have time for full bios.'),

('DIY Tour Planning: Budget Template', 'Sample 7-day DIY tour budget — Expenses: Transportation/gas/tolls $450, Lodging $350, Food $420, Van rental/maintenance $300, Merch restock $500, Promotion/flyers/ads $100, Emergency/misc $150. Total expenses: ~$2,270. Income: Guarantees/door splits $750, Merch sales $1,000, Tips/donations $100, House shows $200. Total income: ~$2,050. Most DIY tours aren''t profitable at first—they''re about exposure, networking, and building fan bases. Minimize costs (crash with friends, cook meals) and maximize merch sales. Over time, guarantees grow and tours shift toward profitability.'),

('DIY Tour Planning: Pre-Tour & On-the-Road Checklist', 'Pre-tour: Create Facebook/Instagram event pages for each show. Ask venues and local artists to help promote. Print and post flyers at coffee shops, record stores, community boards. Design a tour poster and limited-edition tour merch. Rehearse full sets for stamina and polish transitions/banter. On the road: Use Google Sheets for show details, contracts, payments, and merch stock. Keep all receipts. Stay hydrated, get rest, build in strategic rest days. Document everything—it promotes future shows and proves to bookers you''re active and professional.');
